import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Italianno } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Named *-sans so the Tailwind theme key can be `--font-inter` without
// referencing itself. See globals.css.
const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const italianno = Italianno({
  variable: "--font-italianno",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${italianno.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
